### ISSUE TITLE
It should not be possible to re-include a file from an ignored parent directory

### ISSUE THREAD

**Issue by alberto** [kaelzhang/node-ignore#10]
According to the spec:

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. **It is not possible to re-include a file if a parent directory of that file is excluded.** 

Given:
```
var ignore = require('ignore');
var ig = ignore().addPattern(['/abc/', '!/abc/a.js']);
var paths = ['abc/a.js', 'abc/d/e.js'];
ig.filter(paths);
```

Output:
```
[ 'abc/a.js' ]
```

Expected:
```
[]
```

**Comment by kaelzhang** [comment]
Thanks @alberto. It is a good catch. But this module needs a complete refractor.

**Comment by kaelzhang** [comment]
work starts with branch [3.0.0](https://github.com/kaelzhang/node-ignore/tree/3.0.0)

**Comment by kaelzhang** [comment]
Hey, @alberto, I really hope to get your advice.

- do you prefer a sync addIgnoreFile or an async one?
- does it matter to support hierachical .gitignore? One git project might have several `.gitignore` within different directories. And if a ignore pattern acts as a glob pattern, it matches relative to the directory `.gitignore` located at.

> Patterns read from a .gitignore file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the toplevel of the work tree) being overridden by those in lower level files down to the directory containing the file. These patterns match relative to the location of the .gitignore file. A project normally includes such .gitignore files in its repository, containing patterns for files generated as part of the project build.

**Comment by IanVS** [comment]
ESLint is all synchronous for now, so our preference would be to keep it sync.

As for multiple nested ignore files, this is something we've never supported in ESLint.  But, it does seem to be supported by `.gitignore`, and we've said we want our `.eslintignore` to behave the same way as `.gitignore` files, so this seems like it would be a good enhancement.  @nzakas, do you have any thoughts here?

**Comment by kaelzhang** [comment]
Thanks @IanVS. 

When I was working on the job upgrading node-ignore for eslint, I found out some issue for test cases:

- [here](https://github.com/eslint/eslint/blob/master/tests/lib/util/glob-util.js#L211): The file listed to process are absolute paths, but gitignore paths only matches relative paths relative to the same directory of the ignore file. So, is it necessary to add a optional `options.ignoreBase` for `IgnoredPaths`, for the situation if there is only rules but no ignore files.
- [here](https://github.com/eslint/eslint/blob/master/tests/lib/ignored-paths.js#L105): Actually, it is a bug of node-ignore. Empty lines in ignore file should be ignored, even if there're whitespaces. If we want to ignore a file of 3 whitespaces, a `'  \\ '` pattern is needed.

**Comment by kaelzhang** [comment]
I'll check the issue thread tommorrow, because here is time difference between us :smile:

**Comment by IanVS** [comment]
Thanks for investigating and pointing those out.  I'm in the middle of refactoring and cleaning up our use of node-ignore as well as our tests, due to several problems we've seen.  I'd love if you could review my eventual PR (hopefully ready tonight or tomorrow).

**Comment by nzakas** [comment]
> does it matter to support hierachical .gitignore? One git project might have several .gitignore within different directories. And if a ignore pattern acts as a glob pattern, it matches relative to the directory .gitignore located at.

I think it would be nice to support this, but definitely a low priority for us relative to the other ask.

**Comment by kaelzhang** [comment]
I thought I could close this issue now.
