### ISSUE TITLE
Clarity around v6

### ISSUE THREAD

**Issue by JamesHenry** [kaelzhang/node-ignore#138]
Hi Folks,

I received the automated dependency upgrade from renovate here: https://github.com/angular-eslint/angular-eslint/pull/2047 - v6 is indeed on the `latest` tag on npm.

But this repo makes no mention of v6 or what changes are included in it. The Releases tab shows 5.x as still being the latest, and the `CHANGELOG.md` hasn't been updated for a number of years.

Please can you update the repo to reflect the changes that are included in v6?

Many thanks in advance

**Comment by kaelzhang** [comment]
It was my mistake, but I can not revert on npm because npm does not support to unpublish a new version which will make the whole package deprecated. So please just ignore it.

Sorry to disturb.

**Comment by kaelzhang** [comment]
I will always write release notes for all major versions [here](https://github.com/kaelzhang/node-ignore/releases)

**Comment by kaelzhang** [comment]
I will keep this issue open til the next major release.

**Comment by ext** [comment]
Thanks for the clarification, even if the release was unintended maybe you could add it to `CHANGELOG.md` or under releases so other people seeking out this new version can easily find the information.

**Comment by ybiquitous** [comment]
Hi @kaelzhang,

There is almost no diff between 5.3.2 and 6.0.2, but is it intentional?
Introduced files in 6.0.0, such as `index.mjs`, have been removed in 6.0.2. 🤔 

```sh-session
$ npm diff --diff-name-only --diff ignore@5.3.2 --diff ignore@6.0.1
index.js
legacy.js
package.json
index.mjs

$ npm diff --diff-name-only --diff ignore@5.3.2 --diff ignore@6.0.2
package.json

$ npm diff --diff ignore@5.3.2 --diff ignore@6.0.2
diff --git a/package.json b/package.json
index v5.3.2..v6.0.2 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "ignore",
-  "version": "5.3.2",
+  "version": "6.0.2",
   "description": "Ignore is a manager and filter for .gitignore rules, the one used by eslint, gitbook and many others.",
   "files": [
     "legacy.js",

```

**Comment by kaelzhang** [comment]
@ybiquitous  As I said, it was a mistake, making an upgrade to 6.x for now actually changes nothing and does no harm.

**Comment by ybiquitous** [comment]
Got it, sorry for my double comment.

I found the following release page describes that, I hope anyone else could notice the helpful info.
https://github.com/kaelzhang/node-ignore/releases/tag/6.0.1

**Comment by kaelzhang** [comment]
Close for now.
