### ISSUE TITLE
Hangs when using absolute paths

### ISSUE THREAD

**Issue by robert-e-davidson3** [kaelzhang/node-ignore#144]
I (now) know I am not supposed to use absolute paths with this library, but I discovered that when I somehow managed to get a call to `ignores(...)` to hang. Rather than try to figure out myself, I fed Claude Sonnet all of `index.js` and asked it to figure it out for me. So take this report with a grain of salt.

---

Looking at their code, specifically in the `checkPath` function around line 418:

```javascript
const checkPath = (path, originalPath, doThrow) => {
  if (!isString(path)) {
    return doThrow(
      `path must be a string, but got \`${originalPath}\``,
      TypeError
    )
  }

  // We don't know if we should ignore EMPTY, so throw
  if (!path) {
    return doThrow(`path must not be empty`, TypeError)
  }

  // Check if it is a relative path
  if (checkPath.isNotRelative(path)) {
    const r = '`path.relative()`d'
    return doThrow(
      `path should be a ${r} string, but got "${originalPath}"`,
      RangeError
    )
  }

  return true
}
```

The issue is that `doThrow` is being passed as a function but in the options we're seeing `allowRelativePaths = false` is causing it to pass `throwError` which throws synchronously. However, the error isn't being thrown because the error function itself is getting stuck in the infinite recursion before it can throw.

Looking further up at where this is used:

```javascript
_test (originalPath, cache, checkUnignored, slices) {
    const path = originalPath
      && checkPath.convert(originalPath)

    checkPath(
      path,
      originalPath,
      this._allowRelativePaths
        ? RETURN_FALSE  // This branch returns false
        : throwError    // This branch throws
    )
    // ...
}
```

So you're right - it SHOULD throw an error for absolute paths when `allowRelativePaths` is false. The issue is that the performance problem in the path matching is happening before the validation can complete.

This looks like a legitimate bug in the library - it's getting stuck in an infinite loop during path matching before it can validate the path format.

**Comment by kaelzhang** [comment]
@robert-e-davidson3 I added a specific test case for this case [here](https://github.com/kaelzhang/node-ignore/commit/a44c2a7d43865ab576d9eb0f106fcb068f1f1759)

**Comment by robert-e-davidson3** [comment]
Thanks for adding the test. As far as I can tell, Claude is just wrong and the real problem comes from my typescript config, since a simpler one works. I'm still debugging but your code works as expected.

Sorry for the false alarm!
