### ISSUE TITLE
`addIgnoreFile` removed from version 3

### ISSUE THREAD

**Issue by IanVS** [kaelzhang/node-ignore#15]
We use `addIgnoreFile` in ESLint to load in our `.eslintignore` files, but it was removed in version `3.0.0`. Are you planning to re-add this method, as your comment in https://github.com/kaelzhang/node-ignore/issues/10#issuecomment-190657356 seems to indicate?

**Comment by kaelzhang** [comment]
for now, just use 

```
ignore().add(fs.readFileSync(filename))
```

addIgnoreFile will be landed in `3.1.0` to support the base directory of ignore rules
