### ISSUE TITLE
Can't unignore pattern with **

### ISSUE THREAD

**Issue by alberto** [kaelzhang/node-ignore#21]
This works:
```js
const ignore = require('ignore')
var ig = ignore().add(['foo/*', '!foo/bar.js'])
ig.filter(['foo/bar.js'])
[ 'foo/bar.js' ]
```
This doesn't:
```js
const ignore = require('ignore')
var ig = ignore().add(['foo/**', '!foo/bar.js'])
ig.filter(['foo/bar.js'])
[]
```

**Comment by zxqfox** [comment]
Please check this order:
`var ig = ignore().add(['!foo/bar.js', 'foo/**'])`

**Comment by kaelzhang** [comment]
eslint/eslint#5979

- Trailing two asterisks will only match the things inside the current folder, no including the folder itself.
- Several groups of two asterisks will do the right thing.

**Comment by platinumazure** [comment]
I thought the whole point of two asterisks was to avoid having to specify `some/path/*/*/*/*.js`?

**Comment by kaelzhang** [comment]
@platinumazure Yep, I agree

**Comment by alberto** [comment]
Sorry @kaelzhang I am not sure I fully understand what you mean in your description and your reply to @platinumazure (I think he was confused too). Can you provide some code examples?

Ultimately, do you think the fix is correct? From the (few) tests I did in the eslint issue, it looks like it is, matching 0 or more folders.

**Comment by kaelzhang** [comment]
The problem of `3.1.1` is that `'foo/**'` (with 2 trailing asterisks), by mistake, matched the folder `foo`, which caused another problem that the pattern `'!foo/bar.js'` could not unignore `foo/bar.js`, because the parent folder of `foo/bar.js`, i.e. `foo` had been ignored.

According to the spec, `foo/**` should only match the things inside the folder `foo` but not the folder `foo` itself.

`3.1.2` fixes the pattern parser about `foo/**`, and thus fixes the issue #21.

****
@platinumazure was talking about another thing.

**Comment by alberto** [comment]
Cool, thanks. Now I understand the first point. :)

Can you explain the second one, which is what @platinumazure was referering too?

In the end, what I am asking is if there are know issues with `**`

**Comment by kaelzhang** [comment]
The main purpose of `**` is to match infinite depth, which is exactly the case of @platinumazure 

There was an issue that `node-ignore` could not match more than one groups of `/**`, see [here](https://github.com/kaelzhang/node-ignore/commit/3bfb96869396873cc08ab6239f0f08fbd43863f5#diff-1748cb260d7c162374a2d37795ef1ce8L302) and [here](https://github.com/kaelzhang/node-ignore/blob/master/test/ignore.js#L78)(test cases)

**Comment by alberto** [comment]
Awesome. I wasn't sure that was valid in gitignore, but it looks like so. :)

Thanks for fixing this and for the explanation. The reason I nag you with questions and issues instead of reading the code and submitting patches is because I'm not an expert at regular expressions. 😅

**Comment by kaelzhang** [comment]
@alberto Actually, the two asterisks are the linux thing, originally, and it is finally introduced in git `1.8.2`
