### ISSUE TITLE
find in subdirectories is not working client/**/*.js

### ISSUE THREAD

**Issue by CXRom** [kaelzhang/node-ignore#23]
Well in gitignore i can use this kind of expression and its very usefull:

`directory/**/*.js`

Find all the js files in directory folder and all the directory childs too.

**Comment by IanVS** [comment]
Do you have a reproducible test case?

**Comment by kaelzhang** [comment]
@CXRom Right, any reproducible test cases?

****
`directory/**/*.js` will ignore:

```
directory/a.js
directory/a/b/c.js
```

will not ignore

```
a/directory/b.js
a/directory/b/c.js
```

**Comment by CXRom** [comment]
Sorry for late respone. Its working now the problem was with another plugin. Thx a lot!
