### ISSUE TITLE
Incorrect filter management

### ISSUE THREAD

**Issue by icetee** [kaelzhang/node-ignore#25]
Hi @kaelzhang ,

**my filter:**
.git
!.git/config
.ftpconfig

```javascript
0: Object
    negative: false
    origin: ".git"
    pattern: ".git"
    regex: /(?:^|\/)\.git(?=$|\/)/i
1: Object
    negative: true
    origin: "!.git/config"
    pattern: ".git/config"
    regex: /^\.git\/config(?=$|\/$)/i
2: Object
    negative: false
    origin: ".ftpconfig"
    pattern: ".ftpconfig"
    regex: /(?:^|\/)\.ftpconfig(?=$|\/)/i
```

**I use the ignores function, but result (cache):**
D:/ **=> true**
D:/DEV/ **=> true**
D:/DEV/test/ **=> true**
D:/DEV/test/.git/ **=> false**
D:/DEV/test/.git/COMMIT_EDITMSG **=> false**
D:/DEV/test/.git/packed-refs  **=> false**
D:/DEV/test/.git/config  **=> false** || False positive, because this is negative rule!

**Comment by kaelzhang** [comment]
`.gitignore` exactly works in this way.

The [spec](https://git-scm.com/docs/gitignore#_pattern_format) says:

> It is not possible to re-include a file if a parent directory of that file is excluded.

You could sightly change your ignore rules as:

```
.git/*
!.git/config
.ftpconfig
```

I thought it is solved.

**Comment by icetee** [comment]
**No solved my problem!**

I use Windows.

My rules:
```
.git/*
!.git/config
.ftpconfig
```

Accepted:
```
D:/ => true
D:/DEV/ => true
D:/DEV/_incubator/ => true
D:/DEV/_incubator/cubicbox/ => true
D:/DEV/_incubator/cubicbox/.ftpconfig => false [It's OK]
D:/DEV/_incubator/cubicbox/.git/ => true
D:/DEV/_incubator/cubicbox/.git/config => true
D:/DEV/_incubator/cubicbox/.git/description => true [This and other files is bad!]
```

**Comment by kaelzhang** [comment]
@icetee I've added a test spec of your case, and it is ok with windows. See [here](https://ci.appveyor.com/project/kaelzhang/node-ignore/build/job/cav861g7850ktov2) for test result and [here](https://github.com/kaelzhang/node-ignore/commit/22e16ba9984d1c80c829e7bc975d21cceaa16039) for the test case.

Could you please provide any code slices or examples?

And BTW, you should not do something like this on windows:

```js
ignore().add(rules).ignores('D:/DEV/_incubator/cubicbox/.git/description')
``` 

Because `.gitignore` does not works with absolute paths but only relative ones. We should use `path.relative()` method first, then do:

```js
ignore().add(rules).ignores('.git/description')
```

**Comment by kaelzhang** [comment]
Thought it could be closed.

**Comment by icetee** [comment]
@kaelzhang Can you help me?

I write spec in other test file `custom.spec.js`:

```javascript
var ignore = require('../');
var expect = require('chai').expect;

var ig = null;

describe('deep', function() {
  before(function() {
    ig = ignore().add([
      'abc',
      '!abc/b',
    ]);
  });

  it('#0', function() {
    expect(ig.ignores('abc')).to.equal(true); // CORRECT
  });

  it('#1', function() {
    expect(ig.ignores('abcdefg')).to.equal(false); // CORRECT
  });

  it('#2', function() {
    expect(ig.ignores('abc/b')).to.equal(false); // WRONG
  });
});

```

It's as if he did not notice that he was negative. Do I do something wrong?

**Comment by kaelzhang** [comment]
The [gitignore spec](https://git-scm.com/docs/gitignore#_pattern_format) might help you.

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded.

Let me explain that.

The parent directory of `abc/b` is `abc`, and `abc` is ignored, so `abc/b` could not re-include again by the rule `!abc/b`.

The correct way:

```js
ignore().add([
  'abc/*',
  '!abc/b'
]).ignores('abc/b')  
// -> false
```

If `abc` is already ignored, we could

```js
ignore().add([
  // If already ignores
  'abc',
  // It could re-included itself
  '!abc',
  'abc/*',
  '!abc/b'
]).ignores('abc/b')  // -> false
```

**Comment by icetee** [comment]
I understand! Thanks for the help!
