### ISSUE TITLE
ignores() returns unexpected results for some ignored paths with leading "/"

### ISSUE THREAD

**Issue by cpetrov** [kaelzhang/node-ignore#30]
Example:

```js
const ignore = require("ignore");

let ig = ignore().add(['/abc/']) // directory in the beginning of the pathname called "abc"
ig.ignores('./abc/'); // returns false although true is expected
```

This works as expected using `git check-ignore`:

```sh
mkdir /tmp/foobar
cd /tmp/foobar
git init
echo "/abc/" > .gitignore
git check-ignore ./abc/ # returns ./abc/
```

**Comment by kaelzhang** [comment]
`node-ignore` only accepts paths that have been `path.join()`ed, or paths which are the return value of `path.relative()` to the current directory.

```js
ig.ignores(path.join('./abc/'))     // true
```

In most situations, we use `ignore` with `glob` ( or `globby`) whose result only contains the kind of paths.

I want this modules only to care about rules, but not directory structures or anything else. Notice that `git check-ignore` is a cli command which receives an implicit argument, the current working directory. So `cd abc && git check-ignore ../abc/` also returns the directory `../abc/`, which is a non-goal of `node-ignore`.

**Comment by kaelzhang** [comment]
Thought it could be closed.
