### ISSUE TITLE
instanceof breaks in some case

### ISSUE THREAD

**Issue by dmail** [kaelzhang/node-ignore#32]
When using [node-glob-gitignore](https://github.com/kaelzhang/node-glob-gitignore), in specific circumstances I'll describe just after the line below fails and ignore rules gets ignored. https://github.com/kaelzhang/node-ignore/blob/a4118b515ef5d3d411f54722ea076875daaddf49/index.js#L55

### When does it fails ?
Seems related to npm duplicating the dependency to `ignore` in my module and `node-glob-gitignore`. I end up with my node_modules structure having two different `ignore` directory and thus my instances differs what `node-glob-gitignore` is expecting.

### Suggested fix 

```javascript
if (pattern instanceof IgnoreBase) { 
```
Would become 
```javascript
if (pattern && '_rules' in pattern) {
```

**Comment by dmail** [comment]
Until there is a fix I'm using this workaround (converting ignore object back into an array of strings).

```javascript
const createIgnore = require("ignore")
const { glob } = require("glob-gitignore")

const ignore = createIgnore().add('node_modules')
glob(["**/*.js"], {
  ignore: ignore._rules.map(({ origin }) => origin)
})
```

**Comment by kaelzhang** [comment]
Nice catch, buddy 😄 

Landed in `3.3.7`

**Comment by dmail** [comment]
Thank you for the quick fix 👍 
It tooks me some time to figure out what was happening 😫

**Comment by kaelzhang** [comment]
@dmail Really sorry about that 😞

**Comment by dmail** [comment]
@kaelzhang `npm` and `instanceof` are the one to blame, thank you for your work buddy it does the job very well 👍
