### ISSUE TITLE
nesting in node_modules

### ISSUE THREAD

**Issue by quinton-ashley** [kaelzhang/node-ignore#41]
Why does this module nest in a node_modules folder inside the folder of a dependency in the main node_modules folder?  The new behavior since npm 3.11 or something was that all the dependency would be in the main node_modules folder, no more nesting.  Why does `ignore` not adhere to this standard?

**Comment by kaelzhang** [comment]
I thought it is a behavior of `npm` but not `ignore`. And so what is your real problem if `ignore` is not at the root of node_modules folder?

**Comment by quinton-ashley** [comment]
Yes, paths to ignore should be reliable from the main module (ex. `./node_modules/ignore/package.json` the current path is `./node_modules/dependency-that-requires-ignore/node_modules/ignore/package.json`).  As a temporary solution I've fixed the problem by requiring `ignore` in the main module's package.json.  This module should adhere to standard install behavior and not the deprecated behavior of nesting inside other modules.

**Comment by kaelzhang** [comment]
This is not an issue of `ignore`. 

If your code depends on `ignore`, you should add `ignore` as a dependency using `npm i ignore`, and NEVER use the `ignore` module of `dependency-that-requires-ignore`

**Comment by quinton-ashley** [comment]
You're confused.  This is an issue with `ignore`.  No other dependency nests itself like this anymore.  If `ignore` was a dependency of `xyz` and I install `xyz` like one normally would with `npm i xyz` then `ignore` would be at `./node_modules/xyz/node_modules/ignore` but it should be at `./node_modules/ignore`.  This shouldn't be an problem that people installing this package have to solve.  Nesting is improper install behavior that has been deprecated for years.  This will confuse anyone using this package nowadays.  My temp solution of also installing ignore as a dependency of my main project should not be the final solution.  My package does not depend on ignore directly and I have no reason to install `ignore` separately in my main package, I simply want to use `xyz`.  Worse if I want to install a second package,`abc`, that requires `ignore` I will get a separate installation of ignore in that package `./node_modules/abc/node_modules/ignore`.  This is a waste of space and it's why this behavior was deprecated.  I will ask someone at npm if they can help you fix this issue.
