### ISSUE TITLE
ignoring .git

### ISSUE THREAD

**Issue by hlb-schmidt** [kaelzhang/node-ignore#45]
git has its stuff in directory `.git`, so i guess users of git wont have to add `.git` to `.gitignore` cause git ignores it by default.

so, should this library also ignore `.git` by default? (v5.0.2 does not)
or should we add `.git` entry to our `.gitignore`?

**Comment by kaelzhang** [comment]
I prefer no, because `node-ignore` is the underlying library to manage .gitignore rules that we could add the `.git` rule by ourselves.

**Comment by oskude** [comment]
indeed. if user wants to use this library outside git, its better this library does not ignore `.git` by default.

ps. and as i explicitly parse `.gitignore`, ill just add `.git` to the filters in my code.
