### ISSUE TITLE
False positive in isPathValid with Windows paths

### ISSUE THREAD

**Issue by hudochenkov** [kaelzhang/node-ignore#47]
I was [upgrading](https://github.com/stylelint/stylelint/pull/3773) to v5 in `stylelint` and turns out `isPathValid` doesn't validate Windows paths correctly.

```js
isPathValid('..\\foo') // → true, but should be false
```

**Comment by kaelzhang** [comment]
Sorry that I missed the case. Fixed in `5.0.4`

**Comment by hudochenkov** [comment]
Thank you very much!
