### ISSUE TITLE
Question: How to ignore all but some files

### ISSUE THREAD

**Issue by fr43nk** [kaelzhang/node-ignore#51]
Hi,
I use your plugin in my project. My Project is located in `c:\programming\test`.
I have a `.ignore` file in my folder root which is used by ignore like follows:
```
this.ignore.add(readFileSync(join(path.fsPath, ".ignore")).toString());

if( this.ignore.ignores("c:/programming/test/includes/test.log") === false )
  doSomething();

```
The content of my `.ignore` File is
```
*.*
!*.log
```
But this does ignore all files. How can I make this work?

**Comment by kaelzhang** [comment]
- `this.ignore.ignores('includes/test.log')`. Never pass an absolute URL to `.ignores(pathname)`, please check the related [section](https://github.com/kaelzhang/node-ignore#pathname-conventions) carefully.
- The `.ignore file` can be

```
*
!includes
includes/*
!includes/*.log
```
To figure out why, check the 4th paragraph in [PATTERN FORMAT](https://git-scm.com/docs/gitignore#_pattern_format)
