### ISSUE TITLE
Question: Why is . considered a special character that should be escaped?

### ISSUE THREAD

**Issue by kcsparks** [kaelzhang/node-ignore#55]
[Node ignore is treating `.` as a special character and escaping it](https://github.com/kaelzhang/node-ignore/blob/e1dc7a118d1e8967c13d9f8ecd42a9264252471a/index.js#L78).

I am wondering why this is being done? I have looked at the [gitignore docs](https://git-scm.com/docs/gitignore) and the [glob docs](http://man7.org/linux/man-pages/man7/glob.7.html), and cannot find a reference to `.` having a special meaning.

**Comment by kaelzhang** [comment]
It is a special character for JavaScript regular expression but not for .gitignore rules.

**Comment by kcsparks** [comment]
No problems. We just had a misunderstanding about what was being done. Thanks for clearing the mud out of the water!

**Comment by kaelzhang** [comment]
Close for now. If any issues or questions, be free to open a new issue
