### ISSUE TITLE
`isPathValid` does not catch invalid asterisks patterns

### ISSUE THREAD

**Issue by maxwoo-houzz** [kaelzhang/node-ignore#60]
according to the [gitignore spec](https://git-scm.com/docs/gitignore/2.1.4#_pattern_format), more than two asterisks `**` should not be valid, so something like `.abc/*****` should not be allowed. However, `ignore.isPathValid('.abc/*****')` returns `true`.

**Comment by kaelzhang** [comment]
`isValidPath` is not used to check ignore patterns but paths
