### ISSUE TITLE
Ignore rules containing .. as a path element

### ISSUE THREAD

**Issue by jedwards1211** [kaelzhang/node-ignore#64]
This is very minor but I'm just thinking about edge cases in guaranteeing I fully emulate git's behavior.  Git seems to ignore any rules with .. as a path element, but `ignore` doesn't when testing a similarly relative path.

Also `i.ignores('../foo')` will error since the path starts with `../`, but it won't error on `/../` in the middle of the path.

```js
> var i = require("ignore").default()
> i.add('test/../*')
> i.ignores('foo')
false
> i.ignores('test/../foo')
true
```

Whereas with this rule in `.gitignore`, and existing directory `test` and file `foo` in the root dir:
```sh
$ git check-ignore foo || echo not ignored
not ignored
$ git check-ignore test/../foo || echo not ignored
not ignored
```

**Comment by kaelzhang** [comment]
This kind issue is hard to be handled by runtime but by [conventions](https://github.com/kaelzhang/node-ignore#pathname-conventions)

`test/../foo` is actually a path that is not normalized and normalizing a path is the duty of the path module of nodejs

Maybe we could detect if ignore is running in node env and normalize the path before the real logic of `ignores()`

**Comment by jedwards1211** [comment]
Yes I understand that, on the other hand is there any reason ignore shouldn't filter out rules matching `/(^|\/)\.\.($|\/)/`?

**Comment by jedwards1211** [comment]
also maybe this repo shouldn't be named `node-ignore` anymore?  I was thinking the wrapper package I'm planning to make for a node env should be called `node-ignore` 🙃

**Comment by kaelzhang** [comment]
> also maybe this repo shouldn't be named `node-ignore` anymore? I was thinking the wrapper package I'm planning to make for a node env should be called `node-ignore` 🙃

It is a naming convention for myself. I write code in many languages so I use the `node-` prefix to indicate it is a node project.

**Comment by jedwards1211** [comment]
Okay. Do you have any opinion on what I name my npm package for loading rules from files via `fs` and implementing the rest of the gitignore spec?  Possibilities:

* `node-ignore`
* `fs-ignore`
* `ignore-fs`

**Comment by jedwards1211** [comment]
I ended up just making [gitignore-fs](https://github.com/jedwards1211/gitignore-fs)

**Comment by kaelzhang** [comment]
closing this, be free to reopen it if necessary
