### ISSUE TITLE
[Feature] Add export field or new package to render real world gitignore?

### ISSUE THREAD

**Issue by loynoir** [kaelzhang/node-ignore#72]
### Spec
https://git-scm.com/docs/gitignore#_description
- `<DIRS>/.gitignore` 
- `$GIT_DIR/info/exclude`
- `core.excludesFile` = $XDG_CONFIG_HOME/git/ignore || $HOME/.config/git/ignore

### Feature Request
```js
// real world gitignore file list with absolute path
module.exports.excludesFile = [
  <DIRS>/.gitignore,
  $GIT_DIR/info/exclude,
  core.excludesFile
]
```

### Sugar?
```js
// maybe?
module.exports.ignorePatterns = () => render(excludesFile)

// Defaults everyone can agree on
// As `default` is semi-keyword for `ESM`
// Name it same as `github.com/XXX/XXX-sensible`?
module.exports.sensible = () => ignoreLite().add(ignorePatterns())
```

### Usage

```js
// .eslintrc.js
const {ignorePatterns} = require('ignore')
module.exports = {
  ignorePatterns: ignorePatterns()
}
```

### Personal Wish
<details>
  <summary>make `node-ignore` respect environment?</summary>
  <p>

```sh
export NODE_IGNORE_REAL_WORLD=1

// using real world all .gitignore files
eslint .
```
  </p>
</details>

**Comment by kaelzhang** [comment]
I prefer to let this package stay **pure**, env-agnostic and fs-agnostic.

If you want to read some local configurations, it is welcome to create another package based on `node-ignore`

**Comment by kaelzhang** [comment]
I will close this issue, be free to reopen it if necessary
