### ISSUE TITLE
directory ending with / not always correctly ignored

### ISSUE THREAD

**Issue by SamVerschueren** [kaelzhang/node-ignore#77]
Hi!

Thanks for this awesome package! I think I might found a small bug when using it.

With the following `.gitignore` contents

```
c/*
!c/bar.js
```

Running `git check-ignore -v c/` results in 

```
.gitignore:1:c/*        c/
```

Using `ignore.test('c/')` indicates that it's not ignored. This package correctly indicates that `c/` is ignored if I change `c/*` in the `.gitignore` file to `c/`.

Kind regards
Sam

**Comment by kaelzhang** [comment]
Confirmed. Really weird behavior of `git check-ignore`.

IMO, `c/*` means ignoring everything **inside** of directory `c` but not `c` itself

**Comment by SamVerschueren** [comment]
The thing is that `git check-ignore c` is different and not ignored. But with `/` it is. It seems that once you add a `/` and thinks you are IN the directory and it's not the directory itself anymore.

**Comment by kaelzhang** [comment]
But I think this issue will not cause the situation that we copy wrong files, so it is of low priority.

**Comment by SamVerschueren** [comment]
The use case I'm having is that I use [isomorphic-git](https://isomorphic-git.org/en/) which uses this package under the hood. I'm building `git check-ignore` on top of that and that's when I saw that it incorrectly checks the use case explained in the issue.

Would you be open for a PR to try to fix this use case?

**Comment by Thesaintsfan2** [comment]
yes I would

**Comment by dp-dandy** [comment]
It's false advertising to claim that this library is implemented

```
Exactly according to [gitignore man page](http://git-scm.com/docs/gitignore)
``

while this issue is still unresolved

**Comment by kaelzhang** [comment]
> It's false advertising to claim that this library is implemented
> 
> ```
> Exactly according to [gitignore man page](http://git-scm.com/docs/gitignore)
> ```
> 
> while this issue is still unresolved

IMO, the behavior of the git-check-ignore is weird and I still don't know which rule of the http://git-scm.com/docs/gitignore indicates that `c/*` should ignore `c/`.

@dp-dandy Do you have any idea about this?

**Comment by babakfp** [comment]
Hi 👋

Not sure if this is 100% related to the current issue.

I have this in `.gitignore` file:

```
/templates/**/node_modules/
```

When I enter this value to check:

```
templates/SvelteKit/node_modules
```

It says it's not ignored, but it should because Git ignores it.

Removing the ending forward slash fixes the issue, but I don't want to do that because the forward slash indicates to me that it's a folder and not a file.

```
/templates/**/node_modules
```

**Comment by kaelzhang** [comment]
> Hi 👋
> 
> Not sure if this is 100% related to the current issue.
> 
> I have this in `.gitignore` file:
> 
> ```
> /templates/**/node_modules/
> ```
> 
> When I enter this value to check:
> 
> ```
> templates/SvelteKit/node_modules
> ```
> 
> It says it's not ignored, but it should because Git ignores it.
> 
> Removing the ending forward slash fixes the issue, but I don't want to do that because the forward slash indicates to me that it's a folder and not a file.
> 
> ```
> /templates/**/node_modules
> ```

@babakfp 

It is not relevant.

Please check here: https://github.com/kaelzhang/node-ignore?tab=readme-ov-file#2-filenames-and-dirnames

**Comment by kaelzhang** [comment]
@SamVerschueren 

Working on this issue.

First of all, actually, `.ignores()` is not equivalent to `git check-ignore`.

Actually the `c/` in `git check-ignore c/` does not mean the directory `c/` itself, but were considered as a path with something after it.
