### ISSUE TITLE
Find out which paths to watch

### ISSUE THREAD

**Issue by wmertens** [kaelzhang/node-ignore#78]
to set up recursive watchers of paths, it would be a good optimization to skip watching paths if there are no unignored files under them.

Ideally, `filter()` would return a `skip` parameter like node-watch uses: https://github.com/yuanchuan/node-watch/blob/master/README.md#:~:text=skip%20ignored%20directories%20by%20returning%20the%20skip%20flag

Then we'd also need a list of directories that are unignored under ignored directories, so that they can be watched separately.

so e.g.
```
/*/
!/foo/
!/bar/hello/
!/uhm/hello
```

would return `skip` on all paths under root except for `"foo"` and `"uhm"`, and it would have a list of also-to-watch `['/bar/hello']`.

All this is assuming that directories are correctly marked with a trailing `/`; if not they would be considered as files and this would be a safe fallback to recursing.

**Comment by kaelzhang** [comment]
I don't exactly understand your problem

**Comment by wmertens** [comment]
I would like to know, for a given path, if all possible subpaths are ignored, or not.

In other words, is there a matching regex that ignores the path and no unignore regexes that match subpaths?

This knowledge is useful for monitoring a git workdir on Linux for changes. You can't get filesystem events for subtrees so you must recurse, and if a subtree is fully ignored you don't need to recurse into it.

**Comment by kaelzhang** [comment]
In other words, is there a matching regex that ignores the path and no unignore regexes that match subpaths?

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".

From [gitignore spec](http://git-scm.com/docs/gitignore)

And `node-ignore` is an JavaScript implementation according to the gitignore spec

I suggest to understand the usage of .gitignore file

**Comment by kaelzhang** [comment]
```
/*/
!/bar/hello/
```
Will not work expectedly, coz `/bar` is already ignored

Change it to

```
/*
!/bar
/bar/*
!/bar/hello
```
