### ISSUE TITLE
Negative pattern ignored when inside a subdirectory

### ISSUE THREAD

**Issue by seb-mtl** [kaelzhang/node-ignore#79]
Hey there, this is an amazing project.

I am using the following ignore pattern with an unexpected result. Why is `foo/bar/bas` ignored?

```javascript
var ignore = require("ignore");
var ig = ignore();
ig.add(["foo/**", "!foo/bar/bas"]);
ig.filter("foo/bar/bas");
// []
ig.test("foo/bar/bas");
// { ignored: true, unignored: false }
```

Here is the code for a `.gitignore` that ignores `foo/bar/bas`

```bash
git init test
cd test
mkdir -p foo/bar
touch foo/bar/bas
echo "foo/**\n\!foo/bar/bas" > .gitignore
git status
```
Is this a bug?

**Comment by kaelzhang** [comment]
That's how .gitignore works, and `git status` only responses `.gitignore`

From http://git-scm.com/docs/gitignore
> It is not possible to re-include a file if a parent directory of that file is excluded.

**Comment by kaelzhang** [comment]
Feel free to reopen it if you think the issue is still there.
