### ISSUE TITLE
Trailing backslash in the ignore file is throwing a syntax error.

### ISSUE THREAD

**Issue by wkozyra95** [kaelzhang/node-ignore#81]
```
import ignore from 'ignore'
ignore().add('test\\').ignores('test')
```
The above code will throw

`SyntaxError: Invalid regular expression: /(?:^|\/)test\(?=$|\/$)/: Unmatched ')'`

I'm not sure what the correct behavior should be according to standard, but it does not fail in git so I would also expect this case to be handled without throwing an error. For now I'm just handling that case by striping trailing '\', before it's passed to ignore.

**Comment by erunion** [comment]
We're also seeing this issue, but only on Windows.

```js
ignore().add(path.join(process.cwd(), '.git', path.sep));
```

**Comment by kaelzhang** [comment]
I think `test\\` is an invalid gitignore pattern, however it indicates a bug of `node-ignore` that `node-ignore` should not throw

But you should not strip trailing `' '` of gitignore patterns
