### ISSUE TITLE
\# does not work

### ISSUE THREAD

**Issue by Asgator** [kaelzhang/node-ignore#83]
In real code
```
// node v18.5.0
ignore().add('\#abc').ignores('#abc')   // false
```
in documentations
```
ignore().add('\#abc').ignores('#abc')   // true
```

<img width="231" alt="Screenshot 2022-11-21 at 11 30 48" src="https://user-images.githubusercontent.com/5278430/203002439-4768a8c3-3be4-4d4b-a952-1167ee7f9733.png">

**Comment by kaelzhang** [comment]
Oh, it is a typo in doc

which should be

```js
ignore().add('\\#abc').ignore('#abc')  // true
```
