### ISSUE TITLE
Pathname should be a path.relative()d pathname Error with ../ path

### ISSUE THREAD

**Issue by apoorv-2204** [kaelzhang/node-ignore#84]
without path.join
`../exp_aeweb/.git/COMMIT_EDITMSG`
after path.join
`../exp_aeweb/.git/COMMIT_EDITMSG 
`
expected is
`'exp_aeweb/.git/COMMIT_EDITMSG'` 

This is causing the node-ignore to crash.

> path.join('../')
'../'

As path .join dont do much to ../ .

**Comment by kaelzhang** [comment]
Do not do something like this

You'd better use paths like `exp_aeweb/.git/COMMIT_EDITMSG` instead of `../exp_aeweb/.git/COMMIT_EDITMSG`

or you could use the `allowRelativePaths` option which is actually designed for backward compatibility, but strongly not recommended

```js
// not recommended
ignore({
  allowRelativePaths: true
})
```

**Comment by apoorv-2204** [comment]
> Do not do something like this
> 
> You'd better use paths like `exp_aeweb/.git/COMMIT_EDITMSG` instead of `../exp_aeweb/.git/COMMIT_EDITMSG`
> 
> or you could use the `allowRelativePaths` option which is actually designed for backward compatibility, but strongly not recommended
> 
> ```js
> // not recommended
> ignore({
>   allowRelativePaths: true
> })
> ```

thanks
