### ISSUE TITLE
foo/* not correctly respected

### ISSUE THREAD

**Issue by bngo97** [kaelzhang/node-ignore#91]
According to the [man pages](https://git-scm.com/docs/gitignore), 

> The pattern "foo/*", matches "foo/test.json" (a regular file), "foo/bar" (a directory), but it does not match "foo/bar/hello.c" (a regular file), as the asterisk in the pattern does not match "bar/hello.c" which has a slash in it.

This is not correctly respected though.

`ignore().add("docs/*").ignores("docs/foo/bar.txt")` returns true when it should be false for nested files

pretty sure the bug [is here](https://github.com/kaelzhang/node-ignore/blob/master/index.js#L291-#L292) since it's not checking that there are no other paths after the `*`

**Comment by kaelzhang** [comment]
"foo/*" ignores "foo/bar" (including everything under it)

Please understand gitignore better

**Comment by bngo97** [comment]
@kaelzhang I'm sorry, correct me if I'm wrong again  but  "foo/*" should NOT match everything under "foo/bar". It literally says in the documentation `it does not match "foo/bar/hello.c"`. `"foo/**` matches everything inside like you said. But, according to the man pages, `An asterisk "*" matches anything except a slash`

**Comment by kaelzhang** [comment]
It does not match "foo/bar/hello.c", but it matches the folder of the file which is indirectly "ignored" because its parent directory is ignored.

**Comment by bngo97** [comment]
@kaelzhang I see thank you for the clarification! I was planning on using this library to check codeowners for git repos since codeowners is suppose to follow most of the same rules as gitignore but this seems like a divergence. 

I tested this with codeowners and as you can see `foo/temp.txt` has a codeowner but `foo/bar/shows.txt` does not when the codeowners file has `foo/*`. Seems like for gitignores, both of the files match but for codeowners, only one matches

![Screen Shot 2023-03-16 at 10 52 45 AM](https://user-images.githubusercontent.com/22105689/225656555-469122fd-5833-44c7-b67e-4f58f8380b41.png)
![Screen Shot 2023-03-16 at 10 53 15 AM](https://user-images.githubusercontent.com/22105689/225656557-cac55501-36ce-477d-aa30-d9d98185f988.png)
