### ISSUE TITLE
"*.app" ignores "Notificator.app/Contents/PkgInfo"

### ISSUE THREAD

**Issue by Basit-qc** [kaelzhang/node-ignore#95]
I am trying to ignore patterns that end with `.app`
Sample pattern is: `notificator/Notificator.app/Contents/PkgInfo` which should not be ignored.

```
>>> const ig = ignore().add('*.app');
>>> ig.ignores('notificator/Notificator.app/Contents/PkgInfo'));
// Actual output = true
// Expected output = false
```
Kindly let me know if I am not using it correctly, thanks

**Comment by kaelzhang** [comment]
> It seems like it follows `.gitignore` rules, unlike `minimatch`. In that aspect it is working fine. Closing this issue.

Yes, ur right
